# Generated by Django 6.1.1 on 2026-09-08 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0002_comentario_muro_comentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Muro',
            new_name='Post',
        ),
    ]
