# Generated by Django 6.1.1 on 2026-09-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0003_rename_muro_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='post',
            name='comentarios',
            field=models.ManyToManyField(blank=True, related_name='posts', to='muro.comentario'),
        ),
    ]
