# Generated by Django 6.1.1 on 2026-09-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0005_remove_post_comentarios_post_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
