# Generated by Django 6.1.1 on 2026-09-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0006_post_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='estado',
            new_name='activo',
        ),
    ]
